image: maven:3.9.9-eclipse-temurin-17

stages:
  - build
  - test
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn -B -DskipTests clean package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  services:
    - name: testcontainers/ryuk:0.5.1
  script:
    - mvn -B test

docker:
  stage: docker
  image: docker:27.2.0
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

