version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: please-change-me-in-prod-32-bytes-minimum-please
    ports:
      - "8080:8080"
volumes:
  pgdata:


