spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rms}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:please-change-me-in-prod-32-bytes-minimum-please}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:36000}

